name: gitcher
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - gitdb2=2.0.5
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libffi=3.2.1
  - linecache2=1.0.0
  - llvm-meta=7.0.0
  - ncurses=6.1
  - openssl=1.1.1a
  - pip=19.1.1
  - python=3.6.8
  - readline=7.0
  - setuptools=40.7.1
  - six=1.12.0
  - smmap2=2.0.5
  - sqlite=3.26.0
  - tk=8.6.9
  - traceback2=1.4.0
  - unittest2=1.1.0
  - validate_email=1.3
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - funcsigs==1.0.2
    - gitpython==2.1.11
    - mock==2.0.0
    - pbr==5.1.2
    - prettytable==0.7.2

